# Start from the official Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the Python script to the container
COPY simple_input.py .

# Command to run the Python script
CMD ["python", "simple_input.py"]
